version: '3'
services:
  mysql:
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: couponuser
      MYSQL_PASS: 123456
    image: 19215047/mysql:latest
    expose:
      - "3306"
    ports:
      - "23306:3306"
    volumes:
      - "./sqldb/init:/docker-entrypoint-initdb.d/"
      - "./sqldb/conf/my.cnf:/etc/my.cnf"
    security_opt:
      - seccomp:unconfined
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: 19215047/redis:latest
    expose:
      - "6379"
    restart: always
    container_name: redis
    hostname: redis

  web:
    image: 19215047/web:latest
    container_name: web
    hostname: web
    ports:
      - "20080:20080"
    depends_on:
      - mysql
      - redis
    environment:
      WEB_MYSQL_HOST: mysql:3306
      WEB_MYSQL_USER: couponuser
      WEB_MYSQL_PASSWORD: 123456
    restart: always
    command: ["./wait-for-it.sh","mysql:3306","--","sh","./run.sh"]
